export const data = {
    response_code: {
        version: '1.0',
        termsOfService: 'mockURL',
        features: {
            runeNames: 32,
        },
    },
    runeNames: [
        'fehu',
        'uruz',
        'thorn',
        'raido',
        'kaunaz',
        'gyfu',
        'wunjo',
        'ing',
        'tyr',
        'berkana',
        'ehwaz',
        'mannaz',
        'laguz',
        'othala',
        'ansuz',
        'dagaz',
        'hagalaz',
        'nauthiz',
        'isa',
        'jera',
        'eihwaz',
        'peorth',
        'algiz',
        'sowelo',
        'ear',
        'ac',
        'ior',
        'yr',
        'os',
        'cweorth',
        'stan',
        'chalc',
        'gar'
    ]
};
